### ISSUE TITLE
单课程功能

### ISSUE THREAD

**Issue by LX-114** [Changbaiqi/brushlessons#1]
大大 能增加单课程的选项不 有些课 课程开了但老师不让刷

**Comment by Changbaiqi** [comment]
没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。

**Comment by Changbaiqi** [comment]
> 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷

没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。

**Comment by LX-114** [comment]
> > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> 
> 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。

ok的大大

**Comment by Changbaiqi** [comment]
> > > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> > 
> > 
> > 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。
> 
> ok的大大

QQ：2084069833

**Comment by Changbaiqi** [comment]
> > > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> > 
> > 
> > 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。
> 
> ok的大大

功能已实现，详细请查看新版本v1.0.2

**Comment by LX-114** [comment]
> > > > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> > > 
> > > 
> > > 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。
> > 
> > 
> > ok的大大
> 
> 功能已实现，详细请查看新版本v1.0.2

<img width="980" alt="1698771276004" src="https://github.com/Changbaiqi/brushlessons/assets/112723047/4bd96c6b-b780-433e-850a-b78f84e74629">打开exe后闪退

**Comment by Changbaiqi** [comment]
> > > > > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> > > > 
> > > > 
> > > > 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。
> > > 
> > > 
> > > ok的大大
> > 
> > 
> > 功能已实现，详细请查看新版本v1.0.2
> 
> <img alt="1698771276004" width="980" src="https://user-images.githubusercontent.com/112723047/279455077-4bd96c6b-b780-433e-850a-b78f84e74629.png">打开exe后闪退

收到，可能是打包时候的问题，现在正着手修复

**Comment by Changbaiqi** [comment]
> > > > > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> > > > 
> > > > 
> > > > 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。
> > > 
> > > 
> > > ok的大大
> > 
> > 
> > 功能已实现，详细请查看新版本v1.0.2
> 
> <img alt="1698771276004" width="980" src="https://user-images.githubusercontent.com/112723047/279455077-4bd96c6b-b780-433e-850a-b78f84e74629.png">打开exe后闪退

已修复，重新下载v1.0.2版本release即可。

**Comment by LX-114** [comment]
> > > > > > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> > > > > 
> > > > > 
> > > > > 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。
> > > > 
> > > > 
> > > > ok的大大
> > > 
> > > 
> > > 功能已实现，详细请查看新版本v1.0.2
> > 
> > 
> > <img alt="1698771276004" width="980" src="https://user-images.githubusercontent.com/112723047/279455077-4bd96c6b-b780-433e-850a-b78f84e74629.png">打开exe后闪退
> 
> 已修复，重新下载v1.0.2版本release即可。

qq群搜索不到 另新v1.0.2依旧闪退

**Comment by Changbaiqi** [comment]
> > > > > > > 大大 能增加单课程的选项不 有些课 课程开了但老师不让刷
> > > > > > 
> > > > > > 
> > > > > > 没问题，我看看。就是如果有些功需要用户的账号配合着来，不然我无法直接写这个功能，毕竟不知道不让刷的课程他后端的参数是什么。
> > > > > 
> > > > > 
> > > > > ok的大大
> > > > 
> > > > 
> > > > 功能已实现，详细请查看新版本v1.0.2
> > > 
> > > 
> > > <img alt="1698771276004" width="980" src="https://user-images.githubusercontent.com/112723047/279455077-4bd96c6b-b780-433e-850a-b78f84e74629.png">打开exe后闪退
> > 
> > 
> > 已修复，重新下载v1.0.2版本release即可。
> 
> qq群搜索不到 另新v1.0.2依旧闪退

现在应该能搜到了，你加一下群我看看具体报错是什么。这边是运行正常的。
