### ISSUE TITLE
提供学习公社账号测试

### ISSUE THREAD

**Issue by 1302557841** [Changbaiqi/brushlessons#3]
大佬我能提供学习公社账号测试，能否留个邮箱，我发账号密码呢

**Comment by Changbaiqi** [comment]
> 大佬我能提供学习公社账号测试，能否留个邮箱，我发账号密码呢

可加QQ群：932447008。邮箱的话回复比较慢，不是很方便。

**Comment by Changbaiqi** [comment]
学习公社已经成功逆向账号的登录，就差有学习课程的账号用于测试和开发了。

**Comment by Changbaiqi** [comment]
> 大佬我能提供学习公社账号测试，能否留个邮箱，我发账号密码呢

已实现学习公社部分功能，详细可查看v2.0.0-beta.1版本
